version: '2'

# Define the services/containers to be run
services:
  angular:
    build: angular-client # specify the directory of the Dockerfile
    ports:
      - "4200:4200"

  express:
    build: express-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000"

  database:
    image: mongo # specify image to build container from
    ports:
      - "27017:27017"
    volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config: