version: '3'

services:
  angular:
    build: angular-client
    ports:
      - "4200:4200"

  express:
    build: express-server
    command: ["./wait-for-it.sh", "database:27017", "--", "node", "server.js"]
    ports:
      - "3000:3000"

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
volumes:
  mongodb:
  mongodb_config: