version: '3'

services:
  angular:
    build: angular-client
    ports:
      - "4200:4200"
    volumes:
      - ./angular-client/src:/app/src
  express:
    build: express-server
    ports:
      - "3000:3000"
    depends_on:
      - database
  database:
    image: mongo
    ports:
      - "27017:27017"