version: '3'

services:
  angular:
    build: angular-client
    ports:
      - "4200:4200"

  express:
    build: express-server
    ports:
      - "3000:3000"

  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
     - mongodb:/data/db
     - mongodb_config:/data/configdb
volumes:
  mongodb:
  mongodb_config: